# Generated by Django 6.0.6 on 2026-06-29 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Budget period in YYYY-MM format, e.g. "2026-07".', max_length=7)),
                ('allocated_headcount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='buildings.building')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_set', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period', 'building'],
                'constraints': [models.UniqueConstraint(fields=('supervisor', 'building', 'period'), name='unique_supervisor_building_period_budget')],
            },
        ),
    ]
