# Generated by Django 6.0.6 on 2026-06-30 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_supervisor_building_period_budget',
        ),
        migrations.AlterField(
            model_name='budget',
            name='building',
            field=models.ForeignKey(help_text='Headcount quota for this building.', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='set_by',
            field=models.ForeignKey(help_text='Manager who set this quota.', on_delete=django.db.models.deletion.PROTECT, related_name='budgets_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('building', 'period'), name='unique_building_period_budget'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='supervisor',
        ),
    ]
