# Generated by Django 6.0.6 on 2026-06-29 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('i_number', models.CharField(help_text='Student ID, also used as employee identifier.', max_length=50, unique=True, verbose_name='I-Number')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('position_number', models.CharField(max_length=10, verbose_name='Position #')),
                ('is_lead', models.BooleanField(default=False, help_text='Team lead position (suffix -L in original spreadsheet).', verbose_name='Lead')),
                ('shift', models.CharField(blank=True, help_text='e.g. "4:30-7:30 AM"', max_length=50)),
                ('term_status', models.CharField(choices=[('staying', 'Staying'), ('leaving', 'Leaving'), ('new', 'New')], default='staying', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='buildings.building')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['building', 'position_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_authored', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='buildings.building')),
                ('worker', models.ForeignKey(blank=True, help_text='Leave blank for a building-level note.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('absence', 'Absence'), ('no_show', 'No Show'), ('tardy', 'Tardy')], max_length=20)),
                ('subtype', models.CharField(choices=[('absence_1', 'Absence 1'), ('absence_2', 'Absence 2'), ('absence_3', 'Absence 3'), ('absence_4', 'Absence 4'), ('no_show_1', 'No Show 1'), ('no_show_2', 'No Show 2'), ('tardy_1', 'Tardy 1'), ('tardy_2', 'Tardy 2'), ('tardy_3', 'Tardy 3'), ('tardy_4', 'Tardy 4'), ('verbal', 'Verbal'), ('written', 'Written')], max_length=20)),
                ('record_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='workers.worker')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_scores_given', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to='workers.worker')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'year', 'month'), name='unique_worker_monthly_score'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthly_score_valid_month')],
            },
        ),
    ]
