# Generated by Django 6.0.6 on 2026-06-30 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='monthlyscore',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_scores_given', to=settings.AUTH_USER_MODEL, verbose_name='scored by'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='building',
            field=models.ForeignKey(help_text='The building (work site) this position belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='buildings.building'),
        ),
    ]
