# Generated by Django 6.0.6 on 2026-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_building_centric_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position_number',
            field=models.CharField(help_text='Slot number at this building (original spreadsheet "POS #" column). Examples: "1", "2". Team leads use is_lead (suffix -L in the old sheet).', max_length=10, verbose_name='Position slot'),
        ),
    ]
