# Generated by Django 6.0.6 on 2026-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_count_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='record_date',
            field=models.DateField(blank=True, help_text='Leave blank when recording — defaults to today (Mountain Time).'),
        ),
    ]
