# Generated by Django 6.0.6 on 2026-07-21 14:34

import django.db.models.deletion
from django.db import migrations, models


def seed_spring_2026_roster(apps, schema_editor):
    Term = apps.get_model("workers", "Term")
    Worker = apps.get_model("workers", "Worker")
    WorkerTermEnrollment = apps.get_model("workers", "WorkerTermEnrollment")
    spring = Term.objects.filter(name="Spring 2026").first()
    if not spring:
        return
    for worker in Worker.objects.all():
        WorkerTermEnrollment.objects.get_or_create(
            worker=worker,
            term=spring,
            defaults={
                "building_id": worker.building_id,
                "shift": worker.shift,
                "term_status": worker.term_status,
                "status": worker.status,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_supervisor'),
        ('workers', '0008_attendancerecord_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(help_text='BYUI full semester name, e.g. "Spring 2026".', max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='building',
            field=models.ForeignKey(help_text='Work site / department this student employee is assigned to.', on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='buildings.building'),
        ),
        migrations.CreateModel(
            name='WorkerTermEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=50)),
                ('term_status', models.CharField(choices=[('staying', 'Staying'), ('leaving', 'Leaving'), ('new', 'New')], default='staying', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_enrollments', to='buildings.building')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_enrollments', to='workers.term')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_enrollments', to='workers.worker')),
            ],
            options={
                'ordering': ['term', 'building', 'worker__name'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'term'), name='unique_worker_term_enrollment')],
            },
        ),
        migrations.RunPython(seed_spring_2026_roster, migrations.RunPython.noop),
    ]
